name: Check and build

on: [push, pull_request]

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Lint
      uses: golangci/golangci-lint-action@v3
    
    - name: Tidy
      run: bash scripts/tidy.sh

    - name: Test
      run: bash scripts/test.sh

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: invasim
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: bash scripts/build.sh ${BINARY_NAME}
